
services:
  redis:
    image: redis
  web1:
    restart: on-failure
    build: ./web
    hostname: web1
  web2:
    restart: on-failure
    build: ./web
    hostname: web2
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - web1
    - web2
