
services:
  redis:
    image: redis
  web1:
    restart: on-failure
    build: ./web
    hostname: web1
  web2:
    restart: on-failure
    build: ./web
    hostname: web2
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    - '88:88'
    depends_on:
    - dozzle
    - web1
    - web2
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

